version: '3.8'

services:

  db:
    container_name: leetcode_analytics_pg_container
    image: postgres
    restart: always
    # env_file: /Users/venkateshgopalakrishnan/Side Projects/LeetcodePerformanceTracker/.env
    environment:
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_DB: "$POSTGRES_DB"
    ports:
      - "5432:5432"
    volumes:
      - "$DATA_PATH:/var/lib/postgresql/data"