"""save submission_dt as datetime

Revision ID: 758c8260ff3c
Revises: d44f84369943
Create Date: 2022-06-22 23:34:56.861286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758c8260ff3c'
down_revision = 'd44f84369943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_submissions', 'submission_dt',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_submissions', 'submission_dt',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
