"""add time_taken to user_sumbissions table

Revision ID: 77dcca806d47
Revises: 05dc0ab2bfc1
Create Date: 2022-07-03 19:39:22.505696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77dcca806d47'
down_revision = '05dc0ab2bfc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_submissions', sa.Column('time_taken', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_submissions', 'time_taken')
    # ### end Alembic commands ###
