"""updated questions table and new users table

Revision ID: c35b64032caa
Revises: 
Create Date: 2022-06-20 23:54:58.227838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c35b64032caa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=500), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('submission_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submission_status', sa.Enum('Accepted', 'Failed', name='status'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('questions', sa.Column('difficulty_tag', sa.String(length=100), nullable=True))
    op.alter_column('questions', 'url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.create_unique_constraint(None, 'questions', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='unique')
    op.alter_column('questions', 'url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('questions', 'difficulty_tag')
    op.drop_table('users')
    # ### end Alembic commands ###
