"""save submission_dt as datetime

Revision ID: 2d14316a4bff
Revises: 758c8260ff3c
Create Date: 2022-06-22 23:39:16.416785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d14316a4bff'
down_revision = '758c8260ff3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_submissions', sa.Column('submission_dt', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_submissions', 'submission_dt')
    # ### end Alembic commands ###
